coqui-ai/TTS

notebooks/dataset_analysis/CheckDatasetSNR.ipynb

Running notebook brought following error: ```NameError: name 'file_names' is not defined.``` while executing step 7.
As "file_names" hasn't been defined before usage i've to changed it to wav_files.
Additionally i've added link to SNR paper.

Fix for: name 'file_names' is not defined in SNR notebook

---

TTS/utils/io.py

Prevents the following error from appearing when running training on Windows platforms:
```
UnicodeEncodeError: 'charmap' codec can't encode characters in position: character maps to <undefined>
```

Fix `UnicodeEncodeError` on Windows Platforms

---

notebooks/dataset_analysis/CheckSpectrograms.ipynb

This fixes:
```
ModuleNotFoundError: No module named 'tts'
NameError: name 'ipd' is not defined
```
And also performs the following clean-up:
- Fixes how parameters from the config are loaded while still making it possible for them to be overridden on the fly.
- Prints the list of audio files by index.
- Defines a constant to control which audio files gets loaded for all sections.
- Eliminates having to load the audio processor twice.
- Removes output (since it isn't relevant).

Clean-up `CheckSpectrograms.ipynb` and Fix Imports

---

README.md

It was trying to load the model as the config file and failed.
To run the Russian model I also had to omit the vocoder options and edit the config.json to fix an absolute path that was left over from the developer's machine.

Fix the "Run your own TTS and Vocoder models" snippet

---

recipes/ljspeech/tacotron2-DDC/tacotron2-DDC.json

Change default value of `"mixed_precision" : false` as when it is set true it leads to  `raise RuntimeError(f" [!] NaN loss with {key}.")
RuntimeError:  [!] NaN loss with decoder_loss.`

`mixed_precision` set to false

---

CONTRIBUTING.md

Added info in CONTRIBUTING.md to call for people to share models as specified in the pull request [here](https://github.com/coqui-ai/TTS/issues/380)
I have pulled into the main branch because there is no dev code in this and it has only a small amount of changes in the CONTRIBUTING.md file.

added information to ask for model contributions

---

TTS/tts/utils/text/__init__.py
requirements.txt
tests/aux_tests/test_text_processing.py

Minimal modifications for the update to gruut 2.0.
* eSpeak phoneme databases have been re-built with the changes discussed [here](https://github.com/coqui-ai/TTS/issues/680)
* Whitespace is now preserved as per the discussion [here](https://github.com/coqui-ai/TTS/issues/771)
---
For the future: gruut's text processing has been greatly expanded in 2.0, and the current text cleaners in :frog: TTS interfere. For example, the sentence:
```
It is 4pm on 1/2/2013.
```
gets expanded via `phoneme_cleaners` to:
```
It is fourpm on one/two/twenty thirteen.
```
One way to solve this problem would be to use gruut itself as a text cleaner:
```python
import gruut
def gruut_cleaner(text: str, lang: str = "en-us"):
return " ".join(
s.text_with_ws for s in gruut.sentences(text, lang=lang, …
```

Update gruut to version 2.0

---

notebooks/dataset_analysis/CheckSpectrograms.ipynb

Don't use a config.json file but start with the ```BaseAudioConfig```

Update CheckSpectrograms notebook

---

TTS/bin/remove_silence_using_vad.py
TTS/utils/vad.py
requirements.txt

Advantages of the new script against the old one:
1. Better quality in trimming nonspeech parts.
2. Support to all sample rates (I'm using the 8khz [Silero-VAD](https://github.com/snakers4/silero-vad) model and just mapping the time stamps between all possible sample rates >= 8Khz).
3. Now is possible to trim just the beginning and end of the audio (parameter --trim_just_beginning_and_end)

Replace webrtcvad by silero-vad

---

TTS/bin/compute_embeddings.py

Currently is not possible to ignore the eval  partition in compute embeddings. [It happens because the argparser type bool will return  True always](https://stackoverflow.com/questions/44561722/why-in-argparse-a-true-is-always-true).  So I rename the argparse parameter to "no_eval" and set as default False. So now we can disable the eval partition passing --no_eval True.

Bug fix in compute embedding without eval partition

---

TTS/vocoder/datasets/gan_dataset.py
TTS/vocoder/models/gan.py

The order of optimization in the code was wrong.
Follow how the optimization is done in each model:
VITS: 
- forward gen
-  cache gen out
-  forward disc with detach input
-  compute loss disc  + .backward()
- 
-  forward disc
- compute loss gen  + .backward()
Coqui GAN/HiFi-GAN Before this PR:
- forward gen 
- cache gen out
- forward disc 
- compute loss gen  + .backward()
-
- forward disc with detach input
- compute loss disc  + .backward()
HiFi-GAN original repository:
- forward gen
- cache gen out
- forward disc with detach input
- compute loss disc + .backward()
-
- forward disc
- compute loss gen  + .backward()
Coqui GAN/HiFi-GAN After this PR:
- forward gen 
- cache gen out 
- forward disc with detach input 
- compute loss disc + .backward()
-
- forward disc 
- compute loss gen  + …

Fix GAN vocoders Training

---

TTS/tts/models/vits.py

Fix upsampling VITS asserts that was broken.

Fix VITS upsampling asserts

---

TTS/bin/synthesize.py
TTS/tts/models/vits.py
TTS/utils/synthesizer.py
tests/tts_tests/test_vits.py
tests/zoo_tests/test_models.py

I fixed some issues with the voice conversion inference and added a unit test to guarantee that it will not break in the future.

Fix voice conversion inference

---

TTS/tts/utils/managers.py

Added use_cuda argument in self.init_encoder method

Fixed use_cuda issue in compute_embeddings.py

---

TTS/bin/synthesize.py
TTS/utils/manage.py

added support for model_info #1586 
model info can be called using either model_info_by_name or model_info_by_idx. Both return basic information from the .models.json file along with description and default_vocoder (in case of tts_models). If not present, "description" will print "coming soon" and "default_vocder" will print "None". The .models.json file can be updated in future to add additional info in the description field.
Usage : 
`tts --model_info_by_name "<model_type>/<language>/<dataset>/<model_name>"`
The model_info_by_name uses the name as it from the --list_models.
eg.
```
$ tts --model_info_by_name tts_models/tr/common-voice/glow-tts
> model type : tts_models
> language supported : tr
> dataset used : common-voice
> model name : glow-tts
> description : Turkish GlowTTS model …
```

added support for model_info in CLI 

---

MANIFEST.in
TTS/tts/configs/vits_config.py
TTS/tts/layers/losses.py
TTS/tts/models/vits.py
TTS/tts/utils/ssim.py
TTS/utils/synthesizer.py
recipes/ljspeech/fast_pitch/train_fast_pitch.py
recipes/ljspeech/fast_speech/train_fast_speech.py
recipes/ljspeech/speedy_speech/train_speedy_speech.py
recipes/ljspeech/tacotron2-Capacitron/train_capacitron_t2.py
recipes/ljspeech/vits_tts/train_vits.py
recipes/multilingual/vits_tts/train_vits_tts.py
recipes/thorsten_DE/speedy_speech/train_speedy_speech.py
recipes/thorsten_DE/vits_tts/train_vits.py
recipes/vctk/vits/train_vits.py
setup.py
tests/tts_tests/test_vits.py

Implement VitsAudioConfig

---

TTS/tts/models/glow_tts.py

Fix for the __floordiv__ function warning: 
```
glow_tts.py:517: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
```

Fix for FloorDiv Function Warning

---

requirements.txt

New inflect version (6.0) depends on pydantic which has some issues irrelevant to 🐸 TTS. (see #1808) 
Force inflect==5.6 (pydantic free) install to solve dependency issue.

Update requirements.txt; inflect==5.6

---

README.md
TTS/utils/manage.py

- minor PR
- added model_info usage guide based on #1623 in README.md .
- Added 'tqdm' progress bar for model downloads based on feature request #1530 .

Update README.md; download progress bar in CLI.

---

TTS/tts/configs/tacotron_config.py

Running `tts --text "$text" --out_path …` with a somewhat longer
sentences in the text will lead to warnings like “Decoder stopped with
max_decoder_steps 500” and the sentences just being cut off in the
resulting WAV file.
This happens quite frequently when feeding longer texts (e.g. a blog
post) to `tts`. It's particular frustrating since the error is not
always obvious in the output. You have to notice that there are missing
parts. This is something other users seem to have run into as well [1].
This patch simply increases the maximum number of steps allowed for the
tacotron decoder to fix this issue, resulting in a smoother default
behavior.
[1] https://github.com/mozilla/TTS/issues/734

Adjust default to be able to process longer sentences

---

TTS/tts/utils/text/phonemizers/espeak_wrapper.py
TTS/vocoder/models/wavernn.py

Espeak-ng phonemizer sometime produces language flags based on language rulesets. Those flags are kept by the current implementation and forwarded upstream to the tokenizer inducing phoneme mismatches.
With the current implementation:
```python
from TTS.tts.utils.text.phonemizers.espeak_wrapper import ESpeak
e = ESpeak(language="fr-fr")
e.phonemize("Certains mots comme football génèrent des flags de langue", separator="")
e = ESpeak(language="de")
e.phonemize("mein neues bike", separator="")
```
```python
'sɛʁtˈɛ̃ mˈo kɔm (en)fˈʊtbɔːl(fr) ʒenˈɛʁ de- flˈaɡ də- lˈɑ̃ɡ'
#---------------^^^^--------^^^^
'maɪn nˈɔøəs (en)bˈaɪk(de)'
#------------^^^^-----^^^^
```
With the language flags removing:
```python
from TTS.tts.utils.text.phonemizers.espeak_wrapper import ESpeak
e = …
```

Fix language flags generated by espeak-ng phonemizer

---

TTS/tts/layers/tacotron/capacitron_layers.py

crashing for multi speaker training  because of dimension miss match   at line no. 57
[batch, 256] vs [batch , 1, 512]
enc_out = torch.cat([enc_out, speaker_embedding], dim=-1)

capacitron_layers multi speaker bug fix

---

notebooks/dataset_analysis/AnalyzeDataset.ipynb
notebooks/dataset_analysis/PhonemeCoverage.ipynb

Fixes to AnalyzeDataset.ipynb and PhonemeCoverage.ipynb to be compatible with the latest TTS version.
CheckDatasetSRN.ipynb and CheckSpectrograms.ipynb worked without any fixes. I was unable to test CheckPitch.ipynb because of lacking the `fast_pitch/f0_cache` files for LJSpeech.

updates to dataset analysis notebooks

---

TTS/bin/tune_wavegrad.py
TTS/config/__init__.py
TTS/vocoder/datasets/wavegrad_dataset.py

Hello there.
I tried to use script (tune_wavegrad.py), but i had some problems: invalid imports and incorrect vars order in batches.
I made some corrections to the code and the script seems to work fine.

Fix tune wavegrad

---

TTS/.models.json

Add capacitron V2 model to TTS zoo. It's more stable and just as expressive!

Add capacitron v2 model

---

TTS/server/server.py

This fixes an issue where, if you make multiple requests at the same time, the results will sound corrupted or you will get an internal server error.

Fixes a race condition with multiple simultaneous get requests.

---

TTS/config/shared_configs.py
TTS/utils/audio/numpy_transforms.py
TTS/utils/audio/processor.py
requirements.txt
tests/aux_tests/test_audio_processor.py
tests/aux_tests/test_numpy_transforms.py

Replace pyworld by pyin

---

TTS/bin/remove_silence_using_vad.py
TTS/utils/vad.py

Write files with a no-speech warning into a txt file to be able to check later on or remove them from the dataset.

Write non-speech files in a TXT

---

docs/source/tutorial_for_nervous_beginners.md

Currently if one uses the config.json file provided by the tutorial, this error occurs:
```python
$> CUDA_VISIBLE_DEVICES="0" python TTS/bin/train_tts.py --config_path config.json
Traceback (most recent call last):
File "TTS/bin/train_tts.py", line 71, in <module>
main()
File "TTS/bin/train_tts.py", line 51, in main
eval_split_size=config.eval_split_size,
File "/Users/ahmed/dev/TTS/TTS/tts/datasets/__init__.py", line 118, in load_tts_samples
formatter = _get_formatter_by_name(formatter_name)
File "/Users/ahmed/dev/TTS/TTS/tts/datasets/__init__.py", line 165, in _get_formatter_by_name
```
The `load_tts_samples()` function is expecting that the `formatter` field is set, the key word 'name' is nowhere to be found.

Use "formatter" key in the datasets json array

---

TTS/tts/models/base_tts.py
TTS/utils/capacitron_optimizer.py

I needed these changes to get the recipes for capacitron working correctly
* `Trainer` seems to expect `CapacitronOptimizer` to handle `set_to_none` argument
* it appeared that when no special sampler is used, the training set was not being shuffled.
re: the shuffling, these sawtooth patterns appeared in both the step time and loss, but vanished when I set `shuffle=True`

capacitron training fixes

---

requirements.txt

Removing all the languages that are not used by the released models to reduce installation size.

Remove langs expect `en` and `de`

---

.github/workflows/aux_tests.yml
.github/workflows/data_tests.yml
.github/workflows/inference_tests.yml
.github/workflows/text_tests.yml
.github/workflows/tts_tests.yml
.github/workflows/vocoder_tests.yml
.github/workflows/zoo_tests0.yml
.github/workflows/zoo_tests1.yml
.github/workflows/zoo_tests2.yml
TTS/api.py
TTS/utils/manage.py
TTS/utils/synthesizer.py
docs/source/inference.md
tests/inference_tests/test_python_api.py

Early-stage Python API to load and run the released 🐸TTS models.
Feel free to comment...

Python API implementation

---

recipes/vctk/yourtts/train_yourtts.py

@erogol I checked now that the YourTTS recipe is using the default vocabulary (only English).  I think that using the original YourTTS vocabulary is better for the YourTTS recipe because probably the users will try to change the vocabulary and in this way, we already have an example.

Add Original YourTTS vocabulary on YourTTS recipe for full transfer learning

---

TTS/config/shared_configs.py
TTS/tts/datasets/dataset.py
TTS/tts/utils/synthesis.py
TTS/tts/utils/text/phonemizers/base.py
TTS/tts/utils/text/phonemizers/ja_jp_phonemizer.py
TTS/tts/utils/text/phonemizers/ko_kr_phonemizer.py
TTS/tts/utils/text/phonemizers/multi_phonemizer.py
TTS/tts/utils/text/tokenizer.py
recipes/multilingual/vits_tts/train_vits_tts_phonemes.py
tests/text_tests/test_phonemizer.py

Add ability to specify language and tokenizer for each dataset.
```python
from TTS.tts.utils.text.phonemizers.multi_phonemizer import MultiPhonemizer
texts = {
"tr": "Merhaba, bu Türkçe bit örnek!",
"en-us": "Hello, this is English example!",
"de": "Hallo, das ist ein Deutches Beipiel!",
"zh-cn": "这是中国的例子",
}
phonemes = {}
ph = MultiPhonemizer({"tr": "espeak", "en-us": "", "de": "gruut", "zh-cn": ""})
for lang, text in texts.items():
phoneme = ph.phonemize(text, lang)
phonemes[lang] = phoneme
print(phonemes)
```
You set `language` and `phonemizer` for each dataset in the config/recipe. If `phonemizer` is not specified, it's using the default phonemizer for that language.
Also added a recipe to train on mailabs with phonemes. (espeak).

Multilingual tokenizer

---

TTS/.models.json
TTS/tts/configs/vits_config.py
TTS/tts/models/base_tts.py
TTS/tts/models/vits.py
TTS/tts/utils/managers.py
TTS/tts/utils/speakers.py
TTS/utils/manage.py
recipes/vctk/yourtts/train_yourtts.py
tests/tts_tests/test_vits.py
tests/tts_tests/test_vits_d-vectors_train.py
tests/tts_tests/test_vits_multilingual_train-d_vectors.py

Fixes: https://github.com/coqui-ai/TTS/issues/2236

Fixed bug related to yourtts speaker embeddings issue

---

TTS/bin/resample.py
TTS/tts/layers/glow_tts/glow.py
TTS/tts/utils/text/phonemizers/espeak_wrapper.py
pyproject.toml
requirements.txt
setup.py
tests/text_tests/test_phonemizer.py

The distutils package is deprecated¹ and relies on PEP 386² version
comparisons, which have been superseded by PEP 440³ which is implemented
through the packaging module.
With more recent distutils versions, provided through setuptools
vendoring, we are seeing the following exception during version
comparisons:
> TypeError: '<' not supported between instances of 'str' and 'int'
This problem stems from improper version detection in the espeak wrapper,
fixed in a second commit.
A third commit removes the only remaining usage of distutils thereafter.
[1] https://docs.python.org/3/library/distutils.html
[2] https://peps.python.org/pep-0386/
[3] https://peps.python.org/pep-0440/

Use packaging.version for version comparisons

---

TTS/encoder/models/resnet.py

It fix the issue reported on #2348 . Without this PR fixes the speaker encoder is not producing any gradients, and the Speaker Consistency Loss (SCL) has no effect.

Fix Speaker Consistency Loss (SCL)

---

TTS/server/server.py

Added basic Mary-TTS API endpoints to server.py so Coqui-TTS can be used as drop-in replacement for many Mary-TTS compatible services.
Limitations:
- Since Coqui-TTS server usually starts with one specific model loaded the Mary-TTS API will only return this model as single "voice".
Code changes:
- imported `parse_qs` from `urllib.parse` to parse HTTP POST parameters
- imported `render_template_string` from `flask` to return text as endpoint result
- added new routes:
- `/locales` - returns list of locales (currently locale of active model)
- `/voices` - returns list of voices (currently locale and name of active model)
- `/process` - accepts synth. request (GET and POST) with parameter `INPUT_TEXT` (other parameters ignored since we have only one active model)

Basic Mary-TTS API compatibility

---

TTS/tts/models/vits.py

Torch set default value for `return_complex=True` for `torch.stft` method This turned warning into error:-
```
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1591, in fit
self._fit()
File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1544, in _fit
self.train_epoch()
File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1309, in train_epoch
_, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1162, in train_step
outputs, loss_dict_new, step_time = self._optimize(
File "/usr/local/lib/python3.10/dist-packages/trainer/trainer.py", line 1023, in _optimize
outputs, loss_dict = …
```

vits.py training fixed due to return_complex

---

README.md

Running the sample code below results in an error `language_id = self.tts_model.language_manager.name_to_id[language_name]`. The fix is running the code with the correct language strings, the readme has been updated in this PR to work.
I assume this small typo leads to #2456 and #2458
from
```cs
tts.tts_to_file("This is voice cloning.", speaker_wav="my/cloning/audio.wav", language="en", file_path="output.wav")
tts.tts_to_file("C'est le clonage de la voix.", speaker_wav="my/cloning/audio.wav", language="fr", file_path="output.wav")
tts.tts_to_file("Isso é clonagem de voz.", speaker_wav="my/cloning/audio.wav", language="pt", file_path="output.wav")
```
to
```cs
tts.tts_to_file("C'est le clonage de la voix.", speaker_wav="my/cloning/audio.wav", language="fr-fr", file_path="output.wav") …
```

Fixes typo in README.md example code

---

TTS/tts/configs/vits_config.py

Python 3.11 complains about the mutable default and other members were already adapted to use the factory, so I expect this line just went unnoticed until now.
This is the only line I needed to change to get the default speech-synthesis to work in python3.11.
Aside from unpinning dependencies of course.

use default_factory for audio parameter

---

TTS/tts/models/vits.py
TTS/tts/utils/helpers.py

~~Could not get it to output the variable length sequence. Dynamic shapes do not work for some reason. If anyone knows how, feel free to jump in.~~
Thanks to @manmay-nakhashi I fixed the issue. 
This is how it works 
```python 
from TTS.tts.models.vits import Vits
from TTS.tts.configs.vits_config import VitsConfig
from TTS.utils.audio.numpy_transforms import save_wav
config = VitsConfig()
config.load_json("config.json")
vits = Vits.init_from_config(config)
vits.load_checkpoint(config,  "model.pth")
vits.export_onnx()
vits.load_onnx("coqui_vits.onnx")
text = "This is a test"
text_inputs = np.asarray(
vits.tokenizer.text_to_ids(text, language="en"),
dtype=np.int64,
)[None, :]
audio = vits.inference_onnx(text_inputs)
print(audio.shape)
save_wav(wav=audio[0], path="coqui_vits.wav", …
```

Draft ONNX export for VITS

---

TTS/server/server.py

This PR fixes an issue with server.py when --show_details is True.
The `tts_config` and `vocoder_config` arguments were removed in commit 10c988a although `details()` still relies on them. I updated the details function to utilize the new arguments, for both the model and the vocoder configs. This function now works with no model or vocoder, only a model or when a model and vocoder is specified.
Thanks
Chase

fix loading of model and vocoder configs

---

docs/source/finetuning.md

I was reading the finetuning page and just came across some spelling mistakes.

fixed small spelling mistakes finetuning.md

---

TTS/tts/utils/text/japanese/phonemizer.py
requirements.ja.txt
requirements.txt
setup.py

Hello, I am the maintainer of mecab-python3, unidic-lite, and other Japanese related packages. 
Your package uses my packages, but only when dealing with Japanese. My packages are unconditionally required by TTS. However, because my package involves a C++ extension, it is hard to build on M1 Macs. I also do not have the relevant hardware, and so I am unable to distribute wheels for that platform, for details see https://github.com/SamuraiT/mecab-python3/issues/84. 
For roughly a year (https://github.com/SamuraiT/mecab-python3/issues/71), people using TTS have intermittently bothered me about how to build things on OSX or other things I am unable to help with. I [explained how to fix this in December](https://github.com/coqui-ai/TTS/issues/2052#issuecomment-1348481112), but a member of …

Make Japanese-specific dependencies optional

---

TTS/tts/models/vits.py

- Adds multi-language support for VITS onnx
- Fixes #2753 incorrect number of channels when having language_emb_dim > 0 
- Fixes onnx inference error when speaker_id is None or not passed as an argument
- Fixes onnx exporting error `AttributeError: 'Vits' object has no attribute 'disc'` for models with init_discriminator=false
Tested with multi-speaker and multi-language models, and with single speaker and single language, using the following script:
```
import torch
import os
import numpy as np
from TTS.tts.models.vits import Vits
from TTS.tts.configs.vits_config import VitsConfig
from TTS.utils.audio.numpy_transforms import save_wav
modelPath = "MULTILANG_MULTISPEAKER_PATH"
speaker_id = 0 '''None if no multi-speaker model'''
language_id = 0 '''None if no multi-language model'''
config = …
```

Adds multi-language support for VITS onnx, fixes onnx exporting and inference errors

---

recipes/vctk/delightful_tts/train_delightful_tts.py

found some issues whilst trying to train the model myself, here are some improvements for those

Delightful TTS VCTK recipe fixes

---

TTS/server/server.py

This PR add the ability to send POST requests to the /api/tts endpoint, it also adds the ability to utilize headers, with both GET and POST requests. It does not break any existing functionality.
```py
text = request.headers.get('text') or request.values.get("text", "")
```
I'm using `request.headers` to first check if the header exists, if true, the value is set. If false, fall back to URL encoding, utilizing `request.values` which works with both GET and POST requests.
I ran the following code to test each permutation
```py
import requests as re
url = 'http://ip:5002/api/tts'
print(re.get(f"{url}?text=Test GET&speaker_id=p225").status_code)
print(re.get(url, headers={'Text': 'Test GET', 'Speaker-Id':'p225'}).status_code)
print(re.post(f"{url}?text=Test …
```

add post functionality to /api/tts

---

TTS/tts/models/vits.py

- Adds fairseq models onnx support.
- Make load_state_dict strict option configurable for customized fairseq models.
- Fixes random out of index errors in onnx export caused by torch.randint generating char ids higher than model vocab size.
- Fixes onnx export error when there is only a single speaker in a multi-speaker model.
- Fixes onnx inference input mismatch when onnx exportation stripped out unused input arguments. Makes the input arguments variable instead of fixed, based on the real inputs used by the model.
Tested on more than 75 models, with multi-speaker and multi-language models, and single speaker and single language ones.

Add fairseq onnx support and strict configuration, fixes some onnx errors

---

README.md

It's unclear that some of the results in the TTS Performance section are not models; they are human voices.
See this issue: https://github.com/coqui-ai/TTS/issues/2706

Denote human voices in README.md

---

TTS/utils/generic_utils.py

`export XDG_DATA_HOME="/path/to/download"` or `export TTS_HOME="/path/to/download"` will now allow for changing the download path of the models.
Solves https://github.com/coqui-ai/TTS/issues/2680 with @reuben's suggestion.

Add customizable data home path

---

TTS/api.py
TTS/tts/utils/synthesis.py
TTS/utils/synthesizer.py

In https://github.com/coqui-ai/TTS/issues/2282, we proposed up the possibility of implementing a`tts.to(device)` interface as a substitute for `use_cuda` or `gpu` flags. The current flags do not allow users to specify the specific GPU device (e.g., `cuda:3`). It also does not allow users to use other accelerated backends, such as Apple Silicon GPUs ([MPS](https://pytorch.org/docs/stable/notes/mps.html)), which PyTorch now supports.
We make `TTS` and `Synthesizer` classes inherit from `nn.Module`. This gives us `.to(device)` for free for both of the classes. 
We can now run TTS on Apple Silicon (tested on M2 Max). Not all kernels have been implemented in MPS in PyTorch yet, so we need to set the environment variable
```
export PYTORCH_ENABLE_MPS_FALLBACK=1
``` 
to enable CPU fallback. With …

Add device support in TTS and Synthesizer

---

TTS/tts/utils/text/belarusian/phonemizer.py
TTS/tts/utils/text/phonemizers/__init__.py
TTS/tts/utils/text/phonemizers/belarusian_phonemizer.py
recipes/bel-alex73/train_glowtts.py
tests/text_tests/test_belarusian_phonemizer.py

@erogol I'm trying to implement phonemizer for Belarusian language. Could you please to take a look ?
Idea is to call java class from python.
3 things below are required only when Belarusian phonemizer really executed:
- jpype1 module
- JAVA_HOME env variable - points to java installation directory
- BEL_FANETYKA_JAR env variable - points to fanetyka.jar from the https://github.com/alex73/Software-Korpus/releases
I'm not sure about test. I wrote it, but it requires installed java and exists fanetyka.jar. I'm not sure that CoquiTTS test environment will have they.

[WIP] Add phonemizer for Belarusian language

---

requirements.txt

Old scipy version causes an error '_`orrtl: error (200): program aborting due to control-C event`_' when cancelling download function with Ctrl+C, that cannot be handled by try/except block correctly. Because of this, cleanup doesn't work on unsuccessful model download and an error occurs at the next start, because directory already exists. This behavior has been corrected in the new version.

Updated scipy version

---

TTS/utils/manage.py

module 'requests' has no attribute 'Exception' appears when the model download fails (when the domain is blocked, for example).
This PR corrects the exception reference according to: https://requests.readthedocs.io/en/latest/api/#requests.RequestException

Fix requests exception handling in manage.py

---

notebooks/dataset_analysis/CheckSpectrograms.ipynb

The `waveplot` function from 0.8 seems to have been consolidated into `waveshow` in 0.10.

Fixed spectrogram checking on librosa 0.10.x

---

TTS/tts/datasets/formatters.py
recipes/multilingual/cml_yourtts/train_yourtts.py

YourTTS recipe for training using CML-TTS and LibriTTS datasets. It accompanies the model release PR https://github.com/coqui-ai/TTS/pull/2735

Add CML-TTS dataset YourTTS training recipe

---

TTS/tts/models/xtts.py

fix: xtts not taking into account device flag

---

pyproject.toml
requirements.txt

Follows up on https://github.com/coqui-ai/TTS/pull/2990.
Turns out the pinned dependencies cause e.g. my Mac to try and start building Numpy and Pandas from source.
ping @WeberJulian

Loosen dependency pins

---

pyproject.toml

It seems to have been copy-pasted from the Black docs (https://github.com/psf/black/commit/9d749280bb1051991d391e0ee70174a613da16fc) and isn't really relevant here.
(Related to #2992.)

Remove unnecessary black exclude config

---

README.md
TTS/bin/synthesize.py
scripts/sync_readme.py
tests/aux_tests/test_readme.py

This adds tooling to make sure the `description` from `TTS/bin/synthesize.py` is synchronized into the main README.
Help for voice conversion had been missing from the README.

Ensure `tts` CLI tool readme and usage is in sync

---

TTS/api.py

Should prevent that issue, not sure why its set to None though.

None is not able to be read for "XTTS", fixes crash if its set to None.

---

TTS/tts/models/forward_tts.py

fix for bug in https://github.com/coqui-ai/TTS/issues/3020 
I used this command to reproduce: 
`tts --text "बहुत समय पहले की बात है"  --model_name tts_models/hin/fairseq/vits --encoder_path spkr_enc/model_se.pth.tar --encoder_config_path spkr_enc/config_se.json --speaker_wav /raid/datasets/common_voice/cv-corpus-13.0-2023-03-09/de/clips/common_voice_de_18468819.mp3 `

fixed bugs in fastpitch tts synthesis

---

docs/source/main_classes/trainer_api.md
docs/source/models/forward_tts.md

fixed typo of "docs/source/main_classes/trainer_api.md" and "docs/source/models/forward_tts.md"
fundemental -> fundamental 
seprate -> separate

fixed typo of /docs

---

TTS/tts/layers/xtts/tokenizer.py

- Remove necessity of cutlet install when not using Japanese with XTTS
- Preserve [ja] token from the text processing pipeline

Fix xtts v1.1

---

TTS/api.py

issue https://github.com/coqui-ai/TTS/issues/3067

fix for issue 3067

---

.github/workflows/style_check.yml
TTS/api.py
TTS/bin/synthesize.py
TTS/tts/layers/xtts/tokenizer.py
TTS/tts/layers/xtts/zh_num2words.py
TTS/tts/models/xtts.py
TTS/utils/audio/numpy_transforms.py
TTS/utils/audio/processor.py
TTS/utils/synthesizer.py
recipes/ljspeech/xtts_v1/train_gpt_xtts.py
tests/api_tests/test_synthesize_api.py

Split out from #3004.
`make lint` (disabled in 8c1d8df7592459e60d83cd5840f56206cd76ea53) also ran `make style`, so all code since June 2023 had not been `black` + `isort` styled.
This fixes that – aside from `zh_num2words.py`, where I added a `# fmt: off`, so the diff here wouldn't be thousands of lines.

Run `make style` & re-enable it in CI

---

TTS/tts/layers/xtts/tokenizer.py

Add char limit warn

---

TTS/vc/configs/freevc_config.py
TTS/vc/models/freevc.py

Also corrects a mis-copy-pasted type annotation `"VitsConfig"`.

Move FreeVCConfig to TTS.vc.configs (like all other config classes)

---

TTS/utils/manage.py

This removes the hard-coded `model_type` variable, so that the following now returns all models, not only `tts_models`:
```python
from TTS.utils.manage import ModelManager
ModelManager().list_models()
```
The second commit addresses the output of `make lint` for that file.

Fix ModelManager.list_models()

---

TTS/tts/models/xtts.py

When last chunk is empy raises exception with following error
The size of tensor a (0) must match the size of tensor b (1024) at non-singleton dimension 0

Fix for exception on streaming on last chunk

---

TTS/tts/models/xtts.py

Depending on platform and installed libraries, delegate audio loading to torchaudio.
torchaudio<2.1 backend can be selected globally after torchaudio>2.1 backend has changes and ordered backends are used.
Also soundfile>=0.12 made breaking changes and uses now libsndfile packages not platform installed libraries. 
This is one of the reasons with problems on mp3 and mp4 files
With this change for getting latents:
* we can override torchaudio backend (until 2.0.1 at least)
* Windows users can use mp3 files on loading latest (soundfile>0.11 has support for it and as sox backend is not available by default on windows)
* can use sox to Load mp4 files on linux
* can use audiofiles without suffix (as binary file-like objects), which sox/ffmpeg can handle

XTTS- Torchaudio should use proper backend to load audio

---

TTS/tts/layers/delightful_tts/conv_layers.py
TTS/tts/layers/delightful_tts/kernel_predictor.py
TTS/tts/layers/generic/wavenet.py
TTS/tts/layers/glow_tts/glow.py
TTS/tts/layers/tortoise/vocoder.py
TTS/tts/layers/vits/discriminator.py
TTS/tts/layers/xtts/hifigan_decoder.py
TTS/tts/models/xtts.py
TTS/vc/models/freevc.py
TTS/vc/modules/freevc/modules.py
TTS/vc/modules/freevc/wavlm/wavlm.py
TTS/vocoder/layers/hifigan.py
TTS/vocoder/layers/melgan.py
TTS/vocoder/layers/wavegrad.py
TTS/vocoder/models/hifigan_discriminator.py
TTS/vocoder/models/hifigan_generator.py
TTS/vocoder/models/melgan_discriminator.py
TTS/vocoder/models/melgan_generator.py
TTS/vocoder/models/parallel_wavegan_discriminator.py
TTS/vocoder/models/parallel_wavegan_generator.py
TTS/vocoder/models/univnet_discriminator.py
TTS/vocoder/models/univnet_generator.py
TTS/vocoder/models/wavegrad.py
requirements.txt

Implements Changes For Additional PyTorch 2.1 Support:
TORCH.NN.UTILS.WEIGHT_NORM: Function is deprecated. Use torch.nn.utils.parametrizations.weight_norm(), which uses the modern parametrisation API. The new weight_norm is compatible with the state_dict generated from the old weight_norm. (https://pytorch.org/docs/stable/generated/torch.nn.utils.weight_norm.html)
TorchAudio: Migrating the I/O functions to use the dispatcher mechanism (https://pytorch.org/audio/stable/torchaudio.html)

PyTorch 2.1 Updates (Weight Norm and TorchAudio I/O)

---

TTS/tts/layers/xtts/tokenizer.py

This was found w/ ruff:
> F811 Redefinition of unused `preprocess_text` from line 570
I merged the lists of language codes (one list was missing Hungarian) and re-included the Korean check that was missing from one instance of the function.

xtts/tokenizer: merge duplicate implementations of preprocess_text

---

TTS/cs_api.py
TTS/tts/configs/xtts_config.py
TTS/tts/layers/tortoise/dpm_solver.py
TTS/tts/layers/xtts/tokenizer.py
TTS/tts/layers/xtts/trainer/dataset.py
TTS/tts/models/xtts.py
tests/xtts_tests/test_xtts_gpt_train.py
tests/xtts_tests/test_xtts_v2-0_gpt_train.py

Optionally chunk input audio and average the computed latents. It prevents long silences, especially against references with many silent segments.

Update XTTS cloning

---

TTS/tts/layers/xtts/gpt.py

Fixes a bug where the `max_length` value given to the `generate` function was not taking into account the prompt and text.
It was leading to longer text input being cropped in audio sooner than shorter text inputs.

fix max generation length for XTTS

---

TTS/tts/layers/xtts/tokenizer.py
TTS/tts/models/xtts.py

Using `zh` code is more fitting but we currently use `zh-cn` in the config and tokenzier, changing those file would trigger a re-download for everyone using v2. This fix should allow support for both codes.

Fix zh bug

---

TTS/tts/layers/xtts/trainer/gpt_trainer.py
TTS/vocoder/configs/parallel_wavegan_config.py
requirements.txt

Currently,  during GPT XTTS training the DVAE are not in eval mode. This PR fixes it using the new on_train_epoch_start callback from the latest trainer version.
It also fix a issue with parallel wavegan unit test. The target_loss "loss_0" that is the default from GAN vocoder training do not exist for parallel wavegan  and it raises an error with the latest trainer version.

Ensures that only GPT model is in training mode during XTTS GPT training

---

TTS/bin/synthesize.py

In multilingual models, the target language is specified via the `--language_idx` argument. However, the `tts` CLI also accepts a `--language` argument for use with Coqui Studio, so it is easy to choose the wrong one, resulting in the following confusing error at synthesis time:
```
AssertionError:  ❗ Language None is not supported. Supported languages are
['en', 'es', 'fr', 'de', 'it', 'pt', 'pl', 'tr', 'ru', 'nl', 'cs', 'ar',
'zh-cn', 'hu', 'ko', 'ja']
```
This commit adds a better error message when `--language` is passed for a non-studio model.
Fixes #3270, fixes #3291

More informative error for wrong --language argument

---

TTS/tts/utils/text/phonemizers/espeak_wrapper.py

Previously, the text was wrapped in an additional set of quotes that was passed to Espeak. This could result in different phonemization in certain edge cases (it didn't allow to pronounce `A` as a letter) and caused the insertion of an initial separator "_" that had to be removed. Compare:
```
$ espeak-ng -q -b 1 -v en-us --ipa=1 '"A"'
_ˈɐ
```
```
$ espeak-ng -q -b 1 -v en-us --ipa=1 'A'
ˈeɪ
```
Fixes #2619

Don't pass quotes to espeak

---

TTS/api.py
TTS/utils/synthesizer.py

- Fixes #3143 by reverting #3109. The original issue (#3067) was people trying to use `tts.tts_with_vc_to_file()` with XTTS and was "fixed" in #3109. But XTTS has integrated VC and you can just do `tts.tts_to_file(..., speaker_wav="...")`, there is no point in passing it through FreeVC afterwards. So, reverting this commit because it breaks `tts.tts_with_vc_to_file()` for any model that doesn't have integrated VC, i.e. all models this method is meant for.
- Support multi-speaker models in `tts_with_vc/tts_with_vc_to_file`. This didn't work because they set `speaker=None`. Now it's possible to pass a speaker ID.
- Fixes #1440. Passing a `speaker_wav` argument to regular Vits models failed because they don't support voice cloning. Now that argument is simply ignored if there is no speaker …

Fix tts_with_vc

---

TTS/api.py

The logic in api.py to sentence a model  whether is multi-lingual or not is through `model_name`.
https://github.com/coqui-ai/TTS/blob/29dede20d336c8250810575fcdcdbbcad8c40a44/TTS/api.py#L109-L110
but the problem is if the model_name is given then the ModelManager will try to download the model to the output_prefix, which is default to `/home/yhtao/.local/share/tts` in my system. 
```python
tts = TTS(model_path="/mnt/f/model/XTTS-v2_cache/tts_models--multilingual--multi-dataset--xtts_v2/",
config_path="/mnt/f/model/XTTS-v2_cache/tts_models--multilingual--multi-dataset--xtts_v2//config.json").to(device)
```
https://github.com/coqui-ai/TTS/blob/29dede20d336c8250810575fcdcdbbcad8c40a44/TTS/utils/generic_utils.py#L129-L148
of course, there is no model under `/home/yhtao/.local/share/tts`, and …

Misjudgment of `is_multi_lingual` When Loading Multilingual Model via `model_path`

---

CONTRIBUTING.md
Dockerfile
dockerfiles/Dockerfile
dockerfiles/Dockerfile.dev

This is on topic with the issue that I have opened #3262
Mostly a quality of life change that should allow users to develop directly within a Docker container.
The development image (and the contributing instructions) can also be extended to include editor specific instructions.

Introducing Development Dockerfile

---

TTS/api.py
TTS/tts/layers/xtts/trainer/gpt_trainer.py
TTS/utils/manage.py
TTS/utils/synthesizer.py
docs/source/models/xtts.md

This PR allows for running XTTS models with version tags. So you the user can access any version they like.
```python
from TTS.api import TTS
tts = TTS(model_name="xtts_v2.0.2", gpu=True)
tts = TTS(model_name="xtts", gpu=True)
tts.tts_to_file(text="Here is my sample text.",
file_path="output.wav",
speaker_wav=["reference.wav", "reference1.wav"],
language="en")
```
Making automatic sentence splitting optional. So you can apply any custom logic for processing the text before passing it to the model. Set `split_sentences` False. 
```python
from TTS.api import TTS
tts = TTS(model_name="xtts_v2.0.2", gpu=True)
tts.tts_to_file(text="Here is my sample text.",
file_path="output.wav",
speaker_wav=["reference.wav", "reference1.wav"],
language="en",
split_sentences=False)
```

Run XTTS models by direct name with versions

---

TTS/tts/utils/text/punctuation.py
tests/text_tests/test_punctuation.py

Fixes #3333. Stripping and restoring initial punctuation didn't work correctly because the string-splitting caused an additional empty string to be inserted in the text list (because `".A".split(".")` => `["", "A"]`). Now, an initial empty string is skipped and relevant test cases are added.
I also removed some orphaned code to make the rest easier to understand.

fix: correctly strip/restore initial punctuation

---

TTS/demos/xtts_ft_demo/requirements.txt
TTS/demos/xtts_ft_demo/utils/formatter.py
TTS/demos/xtts_ft_demo/utils/gpt_train.py
TTS/demos/xtts_ft_demo/xtts_demo.py
TTS/tts/layers/xtts/trainer/gpt_trainer.py
TTS/tts/models/xtts.py
docs/source/models/xtts.md

This PR has the propose of making XTTS GPT encoder fine-tuning more accessible to beginners users.
It implements a gradio demo that do:
1. Preprocessing of the uploaded audio or audio files in 🐸 TTS coqui formatter
2. Train the XTTS GPT encoder with the processed data
3. Inference support using the fine-tuned model

Add XTTS Fine tuning gradio demo

---

docs/source/models/tortoise.md

Hi!
I propose the following changes to the Tortoise TTS docs. They are two typos I found while browsing the docs.

fix: Few typos in Tortoise docs.

---

TTS/tts/layers/xtts/zh_num2words.py

The pauses in Chinese speech generated by xtts pretrained model are somewhat unnatural.  And I found that punctuation in Chinese text  were replaced with spaces. I replaced punctuation with English comma, and it performs better.
Here's an example:
space
https://github.com/coqui-ai/TTS/assets/44492123/02d8ceb7-8c2c-4b26-9862-e538f97c5c6f
English comma
https://github.com/coqui-ai/TTS/assets/44492123/0be880eb-13ca-4e12-aed2-40e9d77b3a35
Here's the text:
`> Using model: xtts
> Text splitted to sentences.
['在汉字文化圈和海外华人社区中，中文也被称为汉文、华文。', '汉字主要起源于记事的象形性图画，象形字是汉字体系得以形成和发展的基础。', '后来的演变经历
了几千年的漫长历程，经历了甲骨文、金文、篆书、隶书、楷书、草书、行书等阶段，普遍使用楷书。']
> Processing time: 53.86410617828369
> Real-time factor: 1.6633757888038008`
I guess there are few punctuation in Chinese training data, so the pretrained model did …

fix pause problem of Chinese speech

---

docs/source/models/xtts.md

- Remove duplicate of Streaming inference
- Add inference parameters

Add inference parameters

---

TTS/tts/layers/xtts/trainer/gpt_trainer.py

Set the parameter in `recipes/ljspeech/xtts_v2/train_gpt_xtts.py`
```python
OPTIMIZER_WD_ONLY_ON_WEIGHTS = False  # for multi-gpu training please make it False
```
Now we can run a multi-gpu training using DDP back-end like this:
```bash
$ CUDA_VISIBLE_DEVICES="0, 1" python -m trainer.distribute --script recipes/ljspeech/xtts_v2/train_gpt_xtts.py
```
I ran an experiment with 2 GPUs. Everything seems fine.
I saw a TODO here. But I'm not very familiar with this function. I’m not sure if there will be any problems here compared to single GPU training.
```python
def get_optimizer(self) -> List:
"""Initiate and return the optimizer based on the config parameters."""
if self.config.optimizer_wd_only_on_weights:
```

support multiple GPU training for XTTS
