coqui-ai/TTS

- TTS/utils/audio.py
Fix support for windows by storing only the base and not the different log functions.
fix for this issue https://github.com/coqui-ai/TTS/issues/439
> fix windows support

- README.md
Fixed text formatting for url directing to hammer_and_wrench Implementing a New Model in Links and Resources section
> url link formatting for implementing new Model

- TTS/tts/layers/tacotron/tacotron.py
- TTS/tts/layers/tacotron/tacotron2.py
> deleted a line the broke GravesAttention

- TTS/bin/extract_tts_spectrograms.py
- TTS/trainer.py
- TTS/tts/models/align_tts.py
- TTS/tts/models/speedy_speech.py
- TTS/tts/models/tacotron.py
- TTS/tts/models/tacotron2.py
- TTS/utils/arguments.py
Update `SpeakerManager` API to allow replacing old speaker handling functions.
> New speaker manager

- TTS/tts/models/tacotron2.py
should fix https://github.com/coqui-ai/TTS/discussions/496
> fix taco2 speaker-embeddings dimension during inference

- TTS/bin/extract_tts_spectrograms.py
To fix https://github.com/coqui-ai/TTS/issues/571
> Forcing do_trim_silence to False in the extract TTS script

- TTS/bin/train_encoder.py
- tests/test_speaker_encoder_train.py
Training broke down when training with softmax angleproto. The problem has been fixed and new unit tests added to prevent this from happening again.
> Bug fix on train encoder

- TTS/bin/find_unique_chars.py
https://github.com/coqui-ai/TTS/issues/627
> Change to _get_preprocessor_by_name

- TTS/trainer.py
- TTS/tts/models/base_tts.py
- TTS/tts/models/glow_tts.py
- TTS/vocoder/models/__init__.py
- TTS/vocoder/models/wavegrad.py
- TTS/vocoder/models/wavernn.py
- tests/test_speaker_encoder_train.py
Fixing this issue https://github.com/coqui-ai/TTS/issues/634
> [fix] test sentences synthesis

- .github/PR_TEMPLATE.md
> Updated PR_TEMPLATE

- TTS/.models.json
- TTS/tts/utils/text/japanese/phonemizer.py
- tests/text_tests/test_japanese_phonemizer.py
This PR implements Japanese phonemizer that converts alphabets, symbols and numbers to words.
> Japanese phonemizer that converts alphabets, symbols and numbers to words 

- TTS/utils/download.py
- TTS/utils/downloaders.py
Adding kaggle dataset downloader option and more datasets to directly download
> Add addtional datasets

- TTS/bin/compute_embeddings.py
This is a huge time saver with big datasets (especially multilingual) when adding a dataset/files to your config.
> Partial embedding compute

- .github/workflows/data_tests.yml
- Makefile
- TTS/bin/extract_tts_spectrograms.py
- TTS/bin/find_unique_chars.py
- TTS/bin/find_unique_phonemes.py
- TTS/bin/train_tts.py
- TTS/tts/configs/shared_configs.py
- TTS/tts/datasets/__init__.py
- TTS/tts/datasets/formatters.py
- tests/data_tests/test_loader.py
- tests/data_tests/test_samplers.py
The datasets currently use Dict. However, the split_dataset function was using List.
> Fix the bug in split dataset function

- docs/source/main_classes/trainer_api.md
- recipes/ljspeech/hifigan/train_hifigan.py
- recipes/ljspeech/multiband_melgan/train_multiband_melgan.py
- recipes/ljspeech/tacotron2-DDC/train_tacotron_ddc.py
- recipes/ljspeech/univnet/train.py
- recipes/multilingual/vits_tts/train_vits_tts.py
Addressing https://github.com/coqui-ai/TTS/issues/1366
> Fix recipes as to the recent API changes. 

- docs/source/_templates/page.html
Previously docsQA integration was reverted.  6df69f79ea60295a5bb33a72d149697e08873e30
This is to re-integrate docsQA.
Preview: https://tts--preview-jina-ai.netlify.app
> Add docsqa to docs website

- TTS/bin/train_encoder.py
- TTS/speaker_encoder/dataset.py
- TTS/tts/datasets/formatters.py
> REBASED: Add support for the speaker encoder training using torch spectrograms 

- TTS/bin/distribute.py
- TTS/bin/eval_encoder.py
- TTS/bin/synthesize.py
- TTS/bin/train_encoder.py
- TTS/encoder/configs/base_encoder_config.py
- TTS/encoder/dataset.py
- TTS/encoder/losses.py
- TTS/encoder/models/base_encoder.py
- TTS/encoder/models/resnet.py
- TTS/encoder/utils/samplers.py
- TTS/tts/models/base_tts.py
- TTS/tts/models/vits.py
- TTS/tts/utils/speakers.py
- TTS/tts/utils/synthesis.py
- TTS/utils/synthesizer.py
- recipes/ljspeech/hifigan/train_hifigan.py
- recipes/ljspeech/multiband_melgan/train_multiband_melgan.py
- recipes/ljspeech/tacotron2-DDC/train_tacotron_ddc.py
- recipes/ljspeech/univnet/train.py
- recipes/multilingual/vits_tts/train_vits_tts.py
- tests/data_tests/test_samplers.py
> Make Style

- requirements.txt
As we have the "trainer" PyPI package, this updates the requirements
> Update requirements coqui_trainer -> trainer

- CONTRIBUTING.md
> Update CONTRIBUTING.md, fix header

- docs/source/_templates/page.html
More on docsQA:
We figured out a set of better-answered questions.
Hope this improves some user experience.
You can also set the default questions to something else.
To ask more questions, preview: https://tts--preview-jina-ai.netlify.app/
> Improve docsQA default questions

- docs/source/faq.md
This documentation update fixes the issue raised here : https://github.com/coqui-ai/TTS/issues/1536
> Update documentation for multi-gpu training

- TTS/tts/layers/tacotron/attentions.py
> Missing `f` prefix on f-strings fix

- TTS/tts/utils/text/phonemizers/espeak_wrapper.py
This PR fix the bug reported in #1548
> Fix the bug in eSpeak wrapper for eSpeak version 1.48.15

- TTS/tts/datasets/formatters.py
> Add synpaflex formatter

- TTS/vocoder/models/gan.py
> Checkpoint bug fix

- TTS/utils/capacitron_optimizer.py
- recipes/blizzard2013/tacotron1-Capacitron/train_capacitron_t1.py
- recipes/blizzard2013/tacotron2-Capacitron/train_capacitron_t2.py
- updated the recipes activating more losses for more stable training
- re-enabling guided attention loss
- fixed a bug in the capacitron optimizer: correct lr is now fetched for logging
> feat: updated capacitron recipes and lr fix

- requirements.txt
> Update requirements.txt for python 3.10 support

- TTS/tts/models/base_tts.py
- TTS/tts/models/vits.py
function typo leads to training crash, no such function
> fix get_random_embeddings --> get_random_embedding

- TTS/.models.json
- Tacotron2-DDC
- HifiGAN vocoder
> Add new DE Thorsten models

- TTS/bin/find_unique_phonemes.py
- tests/aux_tests/test_find_unique_phonemes.py
> Fix find unique phonemes script

- TTS/tts/utils/text/phonemizers/espeak_wrapper.py
- TTS/tts/utils/text/phonemizers/zh_cn_phonemizer.py
Add espeak support for Chinese and fix the wrong description in 'zh_cn_phonemizer.py'
> Add espeak support for Chinese

- TTS/bin/synthesize.py
- TTS/tts/models/vits.py
It fixes the issue reported on https://github.com/coqui-ai/TTS/discussions/1642 and a bug on inference list_language_idxs parameter
> Minor bug fixes on VITS/YourTTS and inference

- tests/tts_tests/test_tacotron2_model.py
Fix issue from https://github.com/coqui-ai/TTS/issues/2184
> Fix capacitron test when cuda is enabled

- TTS/tts/utils/text/cleaners.py
Added some modifications to the text cleaners so that Catalan can be supported.
> Add Catalan text cleaners for Catalan support

- TTS/server/server.py
- TTS/server/templates/index.html
- TTS/utils/synthesizer.py
It happens that I had an issue about lacking specification for a language when trying multilingual YourTTS locally. This patch fix this (it’s mostly a copy of what is done for speakers).
It also fix two small typo.
> Fix tts-server for multi-lingual models

- TTS/api.py
- TTS/utils/synthesizer.py
- tests/inference_tests/test_python_api.py
- Allow loading models from model files including vocoders.
- Add voice cloning to the API
> API from model path

- requirements.txt
> numpy version for py310

- TTS/tts/models/base_tts.py
OverFlow did not work with test sentences due to some issues in `base_tts.py`. While I encountered it when training OverFlow, since the issue is in BaseTTS it's likely that other subclassed models are affected as well.
> OverFlow with test sentences

- requirements.txt
> Update numba version

- TTS/vocoder/models/hifigan_generator.py
resblock2 description updated.
> [minor] hifigan_generator.py typo

- TTS/tts/models/vits.py
just to make it consistent with language_ids
> [minor] batch["speaker_ids"] getting set two times

- .github/workflows/inference_tests.yml
- README.md
- TTS/api.py
- TTS/utils/synthesizer.py
- docs/source/inference.md
- tests/inference_tests/test_python_api.py
It allows using 🐸Coqui Studio voices and speakers by the TTS API. [More info](https://github.com/coqui-ai/TTS/blob/27a9b26bbdd0b43a3b4ea647f73d37233a233449/docs/source/inference.md)
> 🐸 Coqui Studio API integration 

- TTS/tts/models/vits.py
- TTS/utils/audio/numpy_transforms.py
- TTS/utils/audio/processor.py
- TTS/utils/audio/torch_transforms.py
- requirements.txt
Update Librosa Version To V0.10.0
> Update Librosa Version To V0.10.0

- README.md
- TTS/api.py
- TTS/utils/audio/processor.py
- tests/inference_tests/test_python_api.py
Expose sole voice conversion api
> Api voice conversion

- TTS/api.py
- TTS/bin/synthesize.py
- TTS/utils/manage.py
- tests/inference_tests/test_synthesize.py
This PR enables using [Coqui Studio](https://coqui.ai/) models by `tts` command. Plus small fixups.
> 🐸Studio models by `tts`

- Dockerfile
> lighter docker image

- TTS/tts/models/tortoise.py
Handle changes landed on Transformers==4.30.1
> Fix Tortoise load

- TTS/tts/models/vits.py
This print() will output a vocab array, which should have no meaning to the user.
Anyone in the community is free to review the PR once the tests have passed. If we didn't discuss your PR in Github issues there's a high chance it will not be merged.
Make sure you had fun coding
> delete meaningless print()

- TTS/utils/manage.py
> Resolve conflicts 

- notebooks/dataset_analysis/PhonemeCoverage.ipynb
> Fix phoneme coverage notebook imports

- TTS/tts/layers/tortoise/diffusion.py
- TTS/tts/layers/xtts/diffusion.py
- TTS/tts/layers/xtts/tokenizer.py
- TTS/tts/models/delightful_tts.py
- TTS/vc/modules/freevc/commons.py
This PR removes some inadvertently duplicated functions.
I made sure to check the implementations were also exactly duplicate.
> Duplicate code removal

- docs/source/implementing_a_new_model.md
Fixed typo of docs\source\implementing_a_new_model.md
neccessary -> necessary
> fixed typo of docs\source\implementing_a_new_model.md

- docs/source/formatting_your_dataset.md
Fix this issue: https://discord.com/channels/1037326658807533628/1062887209352581151/1163415313396813854
and this: https://github.com/coqui-ai/TTS/issues/3050
> Fix doc dataset

- TTS/tts/layers/xtts/tokenizer.py
- TTS/tts/models/xtts.py
> Second round of issue fixing for XTTS v1.1

- TTS/tts/datasets/formatters.py
> fix(formatters): set missing root_path attribute

- CONTRIBUTING.md
Just a dumb typo fix in CONTRIBUTING.md.
> fixes a typo
